CREATE TABLE students (
StuID VARCHAR(10) PRIMARY KEY,
lastName VARCHAR(50) NOT NULL,
firstName VARCHAR(50) NOT NULL,
major VARCHAR(50) NOT NULL,
credits INT NOT NULL
);

CREATE TABLE faculty (
facID VARCHAR(10) PRIMARY KEY,
lastName VARCHAR(50) NOT NULL,
department VARCHAR(50) NOT NULL,
ranks VARCHAR(50) NOT NULL
);

CREATE TABLE class (
classNumber VARCHAR(10) PRIMARY KEY,
facId VARCHAR(10) NOT NULL,
schedules VARCHAR(50) NOT NULL,
room VARCHAR(50) NOT NULL
);

CREATE TABLE enroll (
stuID VARCHAR(10) PRIMARY KEY,
classNumber VARCHAR(10) NOT NULL,
grade CHAR(2) NOT NULL
);
